Repository BCG-X-Official/pytools, pull requests merged in 2021-02, with the labels that each got.

#155 BUILD: Bugfix/build/detect changes
  azure-pipelines.yml
Labels: CI/CD, bug

#156 BUILD: do not run nightly builds on weekends
  azure-pipelines.yml
Labels: CI/CD

#154 BUILD: align build requirements pyproject.toml/meta.yaml/tox.ini & across repos
  condabuild/meta.yaml
  make.py
  pyproject.toml
  tox.ini
Labels: CI/CD

#160 BUILD: add bcg_gamma to conda channels in make.py
  make.py
Labels: CI/CD

#159 BUILD: move full make.py paths setup to function set_up
  make.py
Labels: CI/CD

#158 BUILD: eliminate unconstrained build from pipeline
  azure-pipelines.yml
  environment.yml
  make.py
Labels: CI/CD, bug

#157 DOC: update copyright year
  LICENSE
  sphinx/base/conf_base.py
Labels: documentation

#161 BUILD: add message to log completion of build process
  make.py
Labels: CI/CD

#162 BUILD: add support for numpy 1.20
  environment.yml
  pyproject.toml
Labels: CI/CD

#163 BUILD: update environment.yml
  environment.yml
  pyproject.toml
Labels: CI/CD

#164 BUILD: revise veracode scan naming
  azure-pipelines.yml
Labels: CI/CD

#165 BUILD: optimize conda build config
  condabuild/meta.yaml
Labels: CI/CD

#166 API: add protected MatplotStyle method to apply color scheme to Axes object
  src/pytools/viz/_matplot.py
Labels: enhancement

#167 API: make method MatplotStyle._apply_color_scheme public
  src/pytools/viz/_matplot.py
Labels: enhancement

#168 BUILD: refactor conda/tox build code as a Builder class hierarchy
  make.py
Labels: CI/CD

#171 BUILD: update azure-pipelines for new workflow
  azure-pipelines.yml
  test/test/pytools/test_package_version.py
Labels: CI/CD

#169 DOC: restore azure pipelines badge
  README.rst
Labels: documentation

#170 BUILD: use regular pytest & pytest-cov, run pytest nightly
  azure-pipelines.yml
Labels: CI/CD

#178 BUILD: update pipeline conditions for pytest
  azure-pipelines.yml
Labels: CI/CD

#180 REFACTOR: complete type hinting for function compose_meta
  src/pytools/meta/_meta.py
Labels: refactor

#179 TEST: add unit test for docstrings
  make.py
  src/pytools/api/__init__.py
  src/pytools/api/_api.py
  src/pytools/api/_doc_validator.py
  src/pytools/data/_simulation.py
  src/pytools/expression/_expression.py
  src/pytools/expression/atomic/_atomic.py
  src/pytools/expression/base/_base.py
  src/pytools/expression/composite/_composite.py
  src/pytools/expression/composite/base/_base.py
  src/pytools/expression/formatter/_python.py
  src/pytools/fit/_fit.py
  src/pytools/meta/_meta.py
  src/pytools/parallelization/_parallelization.py
  src/pytools/sphinx/_sphinx.py
  src/pytools/text/_text.py
  src/pytools/viz/_matplot.py
  src/pytools/viz/_text.py
  src/pytools/viz/_viz.py
  src/pytools/viz/color/_color.py
  src/pytools/viz/dendrogram/_style.py
  src/pytools/viz/dendrogram/base/_style.py
  src/pytools/viz/distribution/_distribution.py
  src/pytools/viz/distribution/base/_base.py
  src/pytools/viz/matrix/_matrix.py
  test/test/test_docs.py
Labels: CI/CD, documentation

#184 BUILD: set working directory for tox pytest to project root
  condabuild/meta.yaml
  tox.ini
Labels: CI/CD
