Repository BCG-X-Official/pytools, pull requests merged in 2021-01, with the labels that each got.

#126 set the default range of the PercentageMatrix colorbar to [0.0,1.0]
  src/pytools/viz/matrix/_matrix.py
Labels: enhancement

#128 remove badges
  README.rst
Labels: documentation

#129 Improve handling of 3rd party module references in Sphinx documentation
  sphinx/source/_static_base/css/gamma.css
  src/pytools/api/_api.py
  src/pytools/sphinx/_sphinx.py
Labels: documentation, enhancement

#130 refactor ECDF and XYSeries to not base NamedTuple for clearer API & docs
  src/pytools/viz/distribution/base/_base.py
Labels: documentation, refactor

#131 fix typos in cross-references
  src/pytools/expression/base/_base.py
  src/pytools/viz/_viz.py
  src/pytools/viz/dendrogram/base/_style.py
Labels: documentation

#132 restore compatibility with Python 3.6
  src/pytools/expression/atomic/_atomic.py
  src/pytools/sphinx/_sphinx.py
  src/pytools/viz/color/_color.py
Labels: bug

#133 documentation fixes (non-functional)
  src/pytools/viz/_matplot.py
Labels: documentation

#134 Release/1.0.1
  README.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  pypi_description.rst
  pyproject.toml
  sphinx/base/conf_base.py
  sphinx/base/make_base.py
  sphinx/source/faqs.rst
  src/pytools/__init__.py
Labels: release

#135 update doc string for initial package description
  src/pytools/__init__.py
Labels: documentation

#141 BUG: preserve correct instance for subclasses of singleton classes
  src/pytools/meta/_meta.py
Labels: bug

#140 rename branch 1.1 to 1.1.x
  azure-pipelines.yml
Labels: CI/CD

#142 de-duplicate meta-classes and eliminate class 'type' before composing
  src/pytools/meta/_meta.py
Labels: enhancement

#138 update the environment.yml
  environment.yml
Labels: build

#139 API: add oo framework for parallel execution of jobs using joblib
  src/pytools/parallelization/_parallelization.py
Labels: enhancement

#147 DOC: remove flow package from intersphinx list
  sphinx/base/conf_base.py
Labels: documentation

#146 DOC: disable extended timeout for nbsphinx doc build
  sphinx/base/conf_base.py
Labels: documentation

#145 API: sort list of items returned by AllTracker.get_tracked()
  src/pytools/api/_api.py
Labels: enhancement

#144 FIX: support 3rd party documentation for objects with __module__=None
  src/pytools/sphinx/_sphinx.py
Labels: bug

#148 BUILD: add veracode static scan to nightly build pipeline
  azure-pipelines.yml
Labels: CI/CD

#149 FIX: drop support for joblib v0.13
  pyproject.toml
Labels: bug

#150 BUILD: update version numbers
  sphinx/source/faqs.rst
  src/pytools/__init__.py
Labels: CI/CD

#151 BUILD: bump version to 1.0.2
  sphinx/source/faqs.rst
  src/pytools/__init__.py
Labels: CI/CD

#153 BUILD: do not build and publish documentation in nightly builds
  azure-pipelines.yml
Labels: CI/CD, documentation
