Repository BCG-X-Official/pytools, pull requests merged in 2021-04, with the labels that each got.

#222 FIX: version syntax adaptation with mixed = and >=
  make.py
Labels: bug

#221 BUILD: set pytools version to 1.1.2
  src/pytools/__init__.py
Labels: build

#224 BUILD: prepare for release 1.0.3
  RELEASE_NOTES.rst
  src/pytools/__init__.py
Labels: build

#226 BUILD: add Python package version to sphinx, use for FAQs
  sphinx/base/conf_base.py
  sphinx/source/faqs.rst
Labels: API

#229 FIX: do not substitute ~= by ~== when adapting version syntax for tox
  RELEASE_NOTES.rst
  make.py
Labels: bug

#223 API: use background color to render matrix grid to increase contrast
  RELEASE_NOTES.rst
  src/pytools/viz/matrix/_matrix.py
Labels: API

#227 API: support inheriting class docstrings from superclasses in @inheritdoc; add @subsdoc decorator to replace text in docstrings
  RELEASE_NOTES.rst
  src/pytools/api/_api.py
  test/test/pytools/test_api.py
Labels: API

#233 API: prevent casting Expression instances to bool
  src/pytools/expression/_expression.py
  src/pytools/expression/atomic/_atomic.py
  src/pytools/expression/operator/_operator.py
  test/test/pytools/test_expression.py
Labels: API

#232 Release pytools 1.0.5
  RELEASE_NOTES.rst
  azure-pipelines.yml
  sphinx/base/make_base.py
  src/pytools/__init__.py
Labels: release

#237 BUILD: add back required Sphinx make code for docs
  sphinx/base/make_base.py
Labels: bug, build

#236 FIX: return eq_=False when one infix expression is a prefix of the other
  RELEASE_NOTES.rst
  src/pytools/expression/base/_base.py
Labels: bug

#235 FIX: return eq_=False when one infix expression is a prefix of the other
  RELEASE_NOTES.rst
  src/pytools/expression/base/_base.py
Labels: bug
