Repository BCG-X-Official/pytools, pull requests merged in 2021-03, with the labels that each got.

#186 REFACTOR: more modular management of DocValidator validation tests; move tests to module pytools.api.doc
  src/pytools/api/_doc_validator.py
  src/pytools/api/doc/__init__.py
  src/pytools/api/doc/_doc.py
  src/pytools/expression/_expression.py
  test/test/test_docs.py
Labels: refactor

#185 BUILD: prepare pipeline for publishing
  azure-pipelines.yml
Labels: CI/CD

#188 FIX: drawer style start_drawing and finalize_drawing
  src/pytools/viz/_matplot.py
  src/pytools/viz/_text.py
  src/pytools/viz/_viz.py
  src/pytools/viz/dendrogram/_style.py
  src/pytools/viz/dendrogram/base/_style.py
Labels: bug

#187 API: replace forward type references with actual classes in AllTracker
  src/pytools/api/_api.py
Labels: enhancement

#182 Release pytools v1.0.2rc0
  LICENSE
  README.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  make.py
  pyproject.toml
  sphinx/base/conf_base.py
  sphinx/base/make_base.py
  sphinx/source/faqs.rst
  src/pytools/__init__.py
  src/pytools/api/_api.py
  src/pytools/meta/_meta.py
  src/pytools/sphinx/_sphinx.py
  src/pytools/viz/_matplot.py
  test/test/pytools/test_package_version.py
  tox.ini
Labels: CI/CD

#192 DOC: add release notes for 1.0.2
  .idea/pytools.iml
  README.rst
  RELEASE_NOTES.rst
  sphinx/base/make_base.py
  sphinx/source/.gitignore
  sphinx/source/api_landing.rst
  sphinx/source/index.rst
Labels: CI/CD, documentation

#173 BUILD: Release pytools v1.0.2
  .idea/pytools.iml
  LICENSE
  README.rst
  RELEASE_NOTES.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  make.py
  pyproject.toml
  sphinx/base/conf_base.py
  sphinx/base/make_base.py
  sphinx/source/.gitignore
  sphinx/source/api_landing.rst
  sphinx/source/faqs.rst
  sphinx/source/index.rst
  src/pytools/__init__.py
  src/pytools/api/_api.py
  src/pytools/meta/_meta.py
  src/pytools/sphinx/_sphinx.py
  src/pytools/viz/_matplot.py
  test/test/pytools/test_package_version.py
  tox.ini
Labels: CI/CD

#193 BUILD: bump pytools patch version to 1.0.3rc0
  src/pytools/__init__.py
Labels: CI/CD

#194 BUILD: allow to skip package version check based on ENV variable
  azure-pipelines.yml
  test/test/pytools/test_package_version.py
Labels: CI/CD

#195 BUILD: add the bcg_gamma conda channel when building
  make.py
Labels: CI/CD

#197 BUILD: Enforce pre-release for minor and major releases
  test/test/pytools/test_package_version.py
Labels: CI/CD

#196 DOCS: add pre-commit hook instructions to contribution guide
  sphinx/source/contribution_guide.rst
Labels: documentation

#198 BUILD: update flake8 to v3.9.0
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  src/pytools/viz/_viz.py
Labels: CI/CD

#199 API: AllTracker detection/prevention of exporting imported objects and global constants
  RELEASE_NOTES.rst
  src/pytools/api/_api.py
  src/pytools/viz/_matplot.py
  src/pytools/viz/color/_color.py
Labels: enhancement

#200 FIX: prevent infinite recursion in function update_forward_references
  src/pytools/api/_api.py
Labels: bug

#202 FIX: remove reliance on re.Pattern in Python 3.6
  src/pytools/api/_doc_validator.py
Labels: bug

#203 FIX: do not attempt to replace 3rd party documentation for attributes
  src/pytools/sphinx/_sphinx.py
Labels: bug

#204 BUILD: publish to default GitHub pages address only when releasing the latest stable version
  azure-pipelines.yml
  sphinx/base/make_base.py
  src/pytools/__init__.py
Labels: CI/CD

#205 API: rename JobQueue.start() to JobQueue.on_run()
  RELEASE_NOTES.rst
  src/pytools/parallelization/_parallelization.py
Labels: enhancement

#206 Release pytools v1.1.0rc1
  RELEASE_NOTES.rst
  azure-pipelines.yml
  sphinx/base/make_base.py
  src/pytools/__init__.py
  src/pytools/parallelization/_parallelization.py
Labels: release

#208 BUILD: apply make_base.py changes from 1.1.x also on develop
  sphinx/base/make_base.py
Labels: CI/CD

#210 BUILD: prepare for release of pytools 1.1.0
  RELEASE_NOTES.rst
  src/pytools/__init__.py
Labels: CI/CD

#209 DOC: improve docstrings of two implementations of JobQueue.collate()
  src/pytools/parallelization/_parallelization.py
Labels: documentation

#211 Release pytools 1.1.0
  RELEASE_NOTES.rst
  src/pytools/__init__.py
  src/pytools/parallelization/_parallelization.py
Labels: release

#213 BUILD: set pytools to 1.1.1
  sphinx/source/faqs.rst
  src/pytools/__init__.py
Labels: build

#214 BUILD: add copy of old docs-versions folder
  azure-pipelines.yml
Labels: build

#215 BUILD: update version data also on non-latest stable
  sphinx/base/make_base.py
Labels: build

#217 API: use current axes as default in MatplotStyle
  RELEASE_NOTES.rst
  src/pytools/viz/_matplot.py
Labels: API

#216 API: raise exception when running job queues returns wrong # of results
  src/pytools/parallelization/_parallelization.py
Labels: API

#219 FIX: override potential global gridline settings in matplot matrix plots
  src/pytools/viz/matrix/_matrix.py
Labels: bug

#220 Release pytools 1.1.1
  RELEASE_NOTES.rst
  azure-pipelines.yml
  sphinx/base/make_base.py
  sphinx/source/faqs.rst
  src/pytools/__init__.py
  src/pytools/api/_api.py
  src/pytools/parallelization/_parallelization.py
  src/pytools/viz/_matplot.py
  src/pytools/viz/matrix/_matrix.py
Labels: release
