Repository BCG-X-Official/pytools, pull requests merged in 2022-03, with the labels that each got.

#305 FIX: add missing type call
  src/pytools/sphinx/util/_util.py
Labels: bug

#309 FIX: write all log messages to stderr in make.py
  RELEASE_NOTES.rst
  make.py
Labels: bug

#310 BUILD: release pytools 1.1.9
  RELEASE_NOTES.rst
  make.py
  src/pytools/__init__.py
Labels: release

#311 FIX: write all log messages to stderr in make_base.py
  RELEASE_NOTES.rst
  make.py
  sphinx/base/conf_base.py
  sphinx/base/make_base.py
  sphinx/base/make_util.py
  src/pytools/__init__.py
Labels: bug

#312 BUILD: release pytools 1.1.10
  RELEASE_NOTES.rst
  azure-pipelines.yml
  make.py
  sphinx/base/conf_base.py
  sphinx/base/make_base.py
  sphinx/base/make_util.py
  src/pytools/__init__.py
Labels: release

#315 API: make method FittableMixin.ensure_fitted public
  RELEASE_NOTES.rst
  src/pytools/fit/_fit.py
Labels: API

#318 API: replace custom code to parse type hints with call to get_type_hints
  src/pytools/api/_alltracker.py
  src/pytools/api/doc/_doc.py
Labels: bug, API

#319 BUILD: release pytools 2.0.dev7
  src/pytools/__init__.py
  src/pytools/api/_alltracker.py
  src/pytools/api/doc/_doc.py
Labels: release

#320 FIX: flatten args passed to Callable[…].copy_with
  src/pytools/sphinx/util/_util_py37.py
Labels: bug

#321 BUILD: release pytools 2.0.dev8
  src/pytools/__init__.py
  src/pytools/sphinx/util/_util_py37.py
Labels: release
