Repository BCG-X-Official/pytools, pull requests merged in 2024-06, with the labels that each got.

#368 API: build initial Pytools 3.0 release, part 2
  RELEASE_NOTES.rst
  mypy.ini
  src/pytools/expression/_expression.py
  src/pytools/viz/__init__.py
  src/pytools/viz/_html.py
  src/pytools/viz/_text.py
  src/pytools/viz/_viz.py
  src/pytools/viz/dendrogram/_draw.py
  src/pytools/viz/distribution/_distribution.py
  src/pytools/viz/matrix/_matrix.py
  test/test/pytools/test_expression.py
  test/test/pytools/test_sphinx.py
Labels: API

#369 BUILD: release pytools 3.0rc1
  RELEASE_NOTES.rst
  mypy.ini
  src/pytools/__init__.py
  src/pytools/expression/_expression.py
  src/pytools/viz/__init__.py
  src/pytools/viz/_html.py
  src/pytools/viz/_text.py
  src/pytools/viz/_viz.py
  src/pytools/viz/dendrogram/_draw.py
  src/pytools/viz/distribution/_distribution.py
  src/pytools/viz/matrix/_matrix.py
  test/test/pytools/test_expression.py
  test/test/pytools/test_sphinx.py
Labels: release

#371 BUILD: release pytools 2.1.3
  RELEASE_NOTES.rst
  src/pytools/__init__.py
  src/pytools/viz/dendrogram/_style.py
Labels: build

#372 Build/conda channel
  azure-pipelines.yml
  make.py
Labels: build

#370 REFACTOR: upgrade Python syntax to 3.11
  src/pytools/api/_alltracker.py
  src/pytools/api/_api.py
  src/pytools/api/_decorators.py
  src/pytools/api/_doc_validator.py
  src/pytools/api/_missing.py
  src/pytools/api/doc/_doc.py
  src/pytools/asyncio/_asyncio.py
  src/pytools/data/_linkage.py
  src/pytools/data/_matrix.py
  src/pytools/data/_simulation.py
  src/pytools/data/taxonomy/_category.py
  src/pytools/expression/_expression.py
  src/pytools/expression/atomic/_atomic.py
  src/pytools/expression/base/_base.py
  src/pytools/expression/composite/_composite.py
  src/pytools/expression/formatter/_python.py
  src/pytools/expression/operator/_operator.py
  src/pytools/fit/_fit.py
  src/pytools/meta/_meta.py
  src/pytools/parallelization/_parallelization.py
  src/pytools/sphinx/_sphinx.py
  src/pytools/sphinx/util/_util.py
  src/pytools/text/_text.py
  src/pytools/typing/_typing.py
  src/pytools/viz/_matplot.py
  src/pytools/viz/_text.py
  src/pytools/viz/_viz.py
  src/pytools/viz/color/_color.py
  src/pytools/viz/color/_rgb.py
  src/pytools/viz/dendrogram/_draw.py
  src/pytools/viz/dendrogram/_style.py
  src/pytools/viz/dendrogram/base/_style.py
  src/pytools/viz/distribution/_distribution.py
  src/pytools/viz/distribution/base/_base.py
  src/pytools/viz/matrix/_matrix.py
  src/pytools/viz/matrix/base/_base.py
  src/pytools/viz/util/_matplot.py
  test/test/conftest.py
  test/test/pytools/test_api.py
  test/test/pytools/test_dict_repr.py
  test/test/pytools/test_expression.py
  test/test/pytools/test_jobs.py
  test/test/pytools/test_sphinx.py
  test/test/pytools/test_taxonomy.py
  test/test/pytools/test_typing.py
Labels: refactor

#373 API: rename `to_list()`, `to_set()`, etc. to `as_list()`, `as_set()` etc.
  src/pytools/api/_api.py
  src/pytools/api/_doc_validator.py
  src/pytools/data/taxonomy/_category.py
  src/pytools/expression/_expression.py
  src/pytools/parallelization/_parallelization.py
  src/pytools/text/_template.py
  src/pytools/viz/_matplot.py
  test/test/pytools/test_api.py
Labels: API

#374 BUILD: release pytools 3.0.0
  RELEASE_NOTES.rst
  azure-pipelines.yml
  make.py
  src/pytools/__init__.py
  src/pytools/api/_alltracker.py
  src/pytools/api/_api.py
  src/pytools/api/_decorators.py
  src/pytools/api/_doc_validator.py
  src/pytools/api/_missing.py
  src/pytools/api/doc/_doc.py
  src/pytools/asyncio/_asyncio.py
  src/pytools/data/_linkage.py
  src/pytools/data/_matrix.py
  src/pytools/data/_simulation.py
  src/pytools/data/taxonomy/_category.py
  src/pytools/expression/_expression.py
  src/pytools/expression/atomic/_atomic.py
  src/pytools/expression/base/_base.py
  src/pytools/expression/composite/_composite.py
  src/pytools/expression/formatter/_python.py
  src/pytools/expression/operator/_operator.py
  src/pytools/fit/_fit.py
  src/pytools/meta/_meta.py
  src/pytools/parallelization/_parallelization.py
  src/pytools/sphinx/_sphinx.py
  src/pytools/sphinx/util/_util.py
  src/pytools/text/_template.py
  src/pytools/text/_text.py
  src/pytools/typing/_typing.py
  src/pytools/viz/_matplot.py
  src/pytools/viz/_text.py
  src/pytools/viz/_viz.py
  src/pytools/viz/color/_color.py
  src/pytools/viz/color/_rgb.py
  src/pytools/viz/dendrogram/_draw.py
  src/pytools/viz/dendrogram/_style.py
  src/pytools/viz/dendrogram/base/_style.py
  src/pytools/viz/distribution/_distribution.py
  src/pytools/viz/distribution/base/_base.py
  src/pytools/viz/matrix/_matrix.py
  src/pytools/viz/matrix/base/_base.py
  src/pytools/viz/util/_matplot.py
  test/test/conftest.py
  test/test/pytools/test_api.py
  test/test/pytools/test_dict_repr.py
  test/test/pytools/test_expression.py
  test/test/pytools/test_jobs.py
  test/test/pytools/test_sphinx.py
  test/test/pytools/test_taxonomy.py
  test/test/pytools/test_typing.py
Labels: release

#376 BUILD: add support for Python 3.10
  .pre-commit-config.yaml
  RELEASE_NOTES.rst
  azure-pipelines.yml
  environment.yml
  make.py
  mypy.ini
  pyproject.toml
  sphinx/base/bootstrap.py
  sphinx/base/conf_base.py
  sphinx/base/make_base.py
  sphinx/base/make_util.py
  src/pytools/asyncio/_asyncio.py
  src/pytools/data/taxonomy/_category.py
  src/pytools/typing/_typing.py
  test/test/conftest.py
  test/test/pytools/test_dict_repr.py
  test/test/pytools/test_taxonomy.py
  test/test/pytools/viz/dendrogram/test_dendrogram.py
  tox.ini
Labels: API, build

#375 API: log exceptions encountered when calling update_forward_references
  src/pytools/sphinx/util/_util.py
Labels: API, debug

#377 BUILD: release pytools 3.0.1
  .pre-commit-config.yaml
  RELEASE_NOTES.rst
  azure-pipelines.yml
  environment.yml
  make.py
  mypy.ini
  pyproject.toml
  sphinx/base/bootstrap.py
  sphinx/base/conf_base.py
  sphinx/base/make_base.py
  sphinx/base/make_util.py
  src/pytools/__init__.py
  src/pytools/api/_api.py
  src/pytools/asyncio/_asyncio.py
  src/pytools/data/taxonomy/_category.py
  src/pytools/sphinx/util/_util.py
  src/pytools/typing/_typing.py
  test/test/conftest.py
  test/test/pytools/test_dict_repr.py
  test/test/pytools/test_taxonomy.py
  test/test/pytools/viz/dendrogram/test_dendrogram.py
  tox.ini
Labels: release
