Repository BCG-X-Official/pytools, pull requests merged in 2024-07, with the labels that each got.

#379 FIX: support unions, tuples, and `None` with `isinstance_generic`
  RELEASE_NOTES.rst
  src/pytools/typing/_typing.py
  test/test/pytools/test_typing.py
Labels: bug

#362 REFACTOR: Add support for NumPy 2.0
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  src/pytools/data/_linkage.py
  src/pytools/data/_matrix.py
  src/pytools/viz/_matplot.py
  src/pytools/viz/dendrogram/_style.py
  src/pytools/viz/matrix/_matrix.py
  src/pytools/viz/matrix/base/_base.py
  test/test/pytools/viz/dendrogram/test_dendrogram.py
Labels: build

#380 BUILD: release pytools 3.0.2
  .idea/pytools.iml
  .pre-commit-config.yaml
  RELEASE_NOTES.rst
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  src/pytools/__init__.py
  src/pytools/data/_linkage.py
  src/pytools/data/_matrix.py
  src/pytools/typing/_typing.py
  src/pytools/viz/_matplot.py
  src/pytools/viz/dendrogram/_style.py
  src/pytools/viz/matrix/_matrix.py
  src/pytools/viz/matrix/base/_base.py
  test/test/pytools/test_typing.py
  test/test/pytools/viz/dendrogram/test_dendrogram.py
Labels: release
